[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xxxxxx"

[auth.auth0]
client_id = "GajxMFEy4QNAsXCWNYAXS2gf9SeLVNeC"
client_secret = "lqdSKEmZXBudDEqUUPvAUEplsrtDPHnookxcm5CWwMT2PQsAyhgzorpMaKlkUBIt"
server_metadata_url = "https://dev-55zgm5psy21vqbxf.us.auth0.com/.well-known/openid-configuration"  # fmt: skip
client_kwargs = { "prompt" = "login" }